# Generated by Django 2.2.1 on 2019-09-11 02:36

from django.db import migrations, models
import django.db.models.deletion
from django.core.exceptions import ObjectDoesNotExist


def forward_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    PizzaType = apps.get_model("pizza", "PizzaType")
    pizza_types = ['california', 'chicago', 'new york']

    for type in pizza_types:
        try:
            PizzaType.objects.using(db_alias).get(name=type)
        except ObjectDoesNotExist:
            PizzaType.objects.using(db_alias).create(name=type)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizza_transaction', to='pizza.Pizza')),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizza_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizza_types', to='pizza.PizzaType'),
        ),
        migrations.RunPython(forward_func, reverse_func),
    ]
